[theme]
primaryColor = "#c9c9c9"
backgroundColor = "#04044c"
secondaryBackgroundColor = "#04044c"
textColor = "#c9c9c9"

[server]
headless = true

[runner]
systemDependencies = ["libgl1-mesa-glx"]

[browser]
gatherUsageStats = false