#SPOTIFY
SPOTIPY_CLIENT_ID = "e5557a3edfe0413f9babf4fefe546e02"
SPOTIPY_CLIENT_SECRET = "aa8ebb963acc4ffbb79ae4ed396d61ec"
SPOTIFY_USER_ID = "1168069412"

# CLOUDINARY
CLOUDINARY_CLOUD_NAME = "dpylcpsoo"
CLOUDINARY_API_KEY = "874926159578349"
CLOUDINARY_API_SECRET = "phLxggqDlqsgWFpVwTwLk15Hw88"